pipelines:
  - name: my_pipeline_5176
    steps:
      - name: p1_s1_5176
        type: Bash
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - printenv
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"